# A script for comparing the contents of known NES log files
# with those generated by this C++ emulator

import os, sys

path = os.path.dirname(os.path.realpath(__file__))

assert(len(sys.argv) == 3)

# Allow ending before the end of the line, for dealing with cycle count and PPU timing later
END_INDEX = 70

with open(sys.argv[1]) as emuLog:
    with open(sys.argv[2]) as goodLog:
        i = 0
        while emu_line := emuLog.readline():
            ref_line = goodLog.readline()

            ref_addr, ref_opc = ref_line.split()[:2]
            emu_addr, emu_opc = emu_line.split()[:2]

            assert ref_addr == emu_addr, f"Address mismatch on line {i + 1}: {ref_addr} expected, but saw {emu_addr}."
            assert ref_opc == emu_opc, f"Opcode mismatch on line {i + 1}: {ref_opc} expected, but saw {emu_opc}."
            assert ref_line[:END_INDEX] == emu_line[:END_INDEX], f"Line mismatch on line {i + 1}:\nExpected: {ref_line[:END_INDEX]}\nSaw:      {emu_line[:END_INDEX]}"
            i += 1

print("All checks completed successfully.")
