# A script for comparing the contents of known NES log files
# with those generated by this C++ emulator

import os, sys
import difflib

# Adapted from https://stackoverflow.com/questions/32500167/how-to-show-diff-of-two-string-sequences-in-colors
red = lambda text: f"\033[38;2;255;0;0m{text}\033[38;2;255;255;255m\x1b[0m"
green = lambda text: f"\033[38;2;0;255;0m{text}\033[38;2;255;255;255m\x1b[0m"

def get_edits_string(old: str, new: str) -> str:
    codes = difflib.SequenceMatcher(a=old, b=new).get_opcodes()

    def color(opcode):
        match opcode[0]:
            case "equal": return old[opcode[1]:opcode[2]]
            case "delete": return red(old[opcode[1]:opcode[2]])
            case "insert": return green(new[opcode[3]:opcode[4]])
            case "replace": return red(old[opcode[1]:opcode[2]]) + green(new[opcode[3]:opcode[4]])
        
    return ''.join(map(color, codes))


path = os.path.dirname(os.path.realpath(__file__))

assert(len(sys.argv) == 3)

# Allow ending before the end of the line, for dealing with cycle count and PPU timing later
END_INDEX = None

with open(sys.argv[1]) as emuLog:
    with open(sys.argv[2]) as goodLog:
        i = 0
        while emu_line := emuLog.readline():
            ref_line = goodLog.readline()

            if emu_line != ref_line:
                ref_addr, ref_opc = ref_line.split()[:2]
                emu_addr, emu_opc = emu_line.split()[:2]

                assert ref_addr == emu_addr, f"Address mismatch on line {i + 1}: {ref_addr} expected, but saw {emu_addr}."
                assert ref_opc == emu_opc, f"Opcode mismatch on line {i + 1}: {ref_opc} expected, but saw {emu_opc}."

                if END_INDEX:
                    ref_fragment = ref_line[:END_INDEX]
                    emu_fragment = emu_line[:END_INDEX]
                else:
                    ref_fragment = ref_line
                    emu_fragment = emu_line
                assert ref_fragment == emu_fragment, f"Line mismatch on line {i + 1}:\nExpected: {ref_fragment}Saw:      {emu_fragment}Edits:    {get_edits_string(ref_fragment, emu_fragment)}"
            i += 1

print("All checks completed successfully.")
