name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux-gcc:
    runs-on: ubuntu-24.04

    name: "Linux - GCC / Ninja"

    steps:
    - uses: actions/checkout@v4

    - name: Download SDL2
      run: sudo apt-get install libsdl2-dev

    - name: Configure CMake
      run: cmake --preset=linux-gcc-ninja-release-ci

    - name: Build
      run: cmake --build build --parallel

    - name: Test
      working-directory: build
      run: ctest --output-on-failure

  build-windows:
    runs-on: windows-latest

    name: Windows - MSVC / MSBuild

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake --preset=windows-msvc-release-ci

    - name: Build
      # Build type required for multi-configuration generators
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

    - name: Test
      working-directory: build
      # Build type required for multi-configuration generators
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
